---
title: "NYC Air Quality Dashboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard) #load libraries
library(leaflet)
library(tidyverse)
library(data.table)
library(shiny)
library(plotly)
library(mgcv)
library(RColorBrewer)
library(zoo)
library(lubridate)

theme_set(theme_minimal() + theme(legend.position = "bottom")) #theming
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r 2020 air quality data cleaning, include = FALSE}
# Data import and cleaning
AQI_2020 = fread("./data/waqi-covid19-airqualitydata-2020.csv") %>%
  janitor::clean_names() %>% 
  filter(country == "US") %>%
  filter(city == "Brooklyn" | city == "Queens" | city == "The Bronx" | city == "Staten Island" | city == "Manhattan") %>%
  mutate(borough = city) %>%
  select(-c(city, country)) %>%
  pivot_wider(names_from = "specie", values_from = c("count", "min", "max", "median", "variance")) %>% 
  select(date, borough, median_pm25, median_o3, median_co, median_no2)

# Write functions that calculate the individual AQI (IAQI) for each individual pollutant and account for missing values
IAQI_formula_o3 = function(AQI){ #ozone
  if (is.na(AQI) == TRUE) { 
    AQI_o3 = 0
  }
  
  else if (AQI <= 54 && AQI >= 0 ) {
    IAQI_o3 = (50/54)*(AQI - 0) + 0
  }
  
  else if (AQI <= 70 && AQI > 54 ) {
    IAQI_o3 = (50/22)*(AQI - 55) + 51
  }
  
  else if (AQI <= 85 && AQI > 70) {
    IAQI_o3 = (50/14)*(AQI - 70) + 101
  }
  
  else if (AQI <= 105 && AQI > 85 ) {
    IAQI_o3 = (50/19)*(AQI - 86) + 151
  }
  
  else if (AQI <= 200 && AQI > 105 ) {
    IAQI_o3 = (99/94)*(AQI - 106) + 201
  }
  
  else if (AQI <= 404 && AQI > 204) {
    IAQI_o3 = (99/199)*(AQI - 205) + 201
  }
  
  else{
    IAQI_o3 = (199/199)*(AQI - 405) + 301
  }
}
IAQI_formula_pm25 = function(AQI){
  if (is.na(AQI) == TRUE) { #particular matter 2.5
    IAQI_pm25 = 0
  }
  
  else if (AQI <= 12 && AQI >= 0 ) {
    IAQI_pm25 = (50/12)*(AQI - 0) + 0
  }
  
  else if (AQI <= 35.4 && AQI >= 12.1 ) {
    IAQI_pm25 = (50/23.3)*(AQI - 12.1) + 51
  }
  
  else if (AQI <= 55.4 && AQI >= 35.5 ) {
    IAQI_pm25 = (50/19.9)*(AQI - 35.5) + 101
  }
  
  else if (AQI <= 150.4 && AQI >= 55.5 ) {
    IAQI_pm25 = (50/94.9)*(AQI - 55.5) + 151
  }
  
  else{
    IAQI_pm25 = (99/99.9)*(AQI - 150.5) + 201
  }
}
IAQI_formula_co = function(AQI){
  if (is.na(AQI) == TRUE) { #index
    IAQI_co = 0
  }
  
  else if (AQI <= 4.4 && AQI >= 0) {
    IAQI_co = (50/4.4)*(AQI - 0) + 0
  }
  
  else if (AQI <= 9.4 && AQI >= 4.5 ) {
    IAQI_co = (50/4.9)*(AQI - 4.5) + 51
  }
  
  else{
    IAQI_co = (199/19.9)*(AQI - 30.5) + 301
  }
}
IAQI_formula_no2 = function(AQI){
  if (is.na(AQI) == TRUE) { #nitrogen dioxide
    IAQI_no2 = 0
  }
  
  else if (AQI <= 53 && AQI >= 0 ) {
    IAQI_no2 = (50/53)*(AQI - 0) + 0
  }
  
  else if (AQI <= 100 && AQI >= 54 ) {
    IAQI_no2 = (50/46)*(AQI - 54) + 51
  }
  
  else{
    IAQI_no2 = (50/259)*(AQI - 101) + 101
  }
}
# Generate IAQIs, determine AQI and AQI category based on max IAQI per day, for 2020
AQI_2020 = #map the functions over median values and store the result in an IAQI variable, then mutate to create a categorical variable
  AQI_2020 %>% 
  mutate(
    IAQI_o3 = map(median_o3, IAQI_formula_o3),
    IAQI_pm25 = map(median_pm25, IAQI_formula_pm25),
    IAQI_co = map(median_co, IAQI_formula_co),
    IAQI_no2 = map(median_no2, IAQI_formula_no2)
    ) %>% 
  rowwise() %>% 
  mutate(
    AQI = max(IAQI_o3, IAQI_pm25, IAQI_co, IAQI_no2, na.rm = TRUE), # Taking max of the individual AQI scores, right?
    AQI_category =
      if_else(
        AQI <= 50 & AQI >= 0,
        "Good",
        if_else(
          AQI <= 100 & AQI > 50,
          "Moderate",
          if_else(
            AQI <= 150 & AQI > 100,
            "Unhealthy for Sensitive Populations",
            "Unhealthy")
          )
        ),
    IAQI_o3 = unlist(IAQI_o3),
    IAQI_pm25 = unlist(IAQI_pm25),
    IAQI_co = unlist(IAQI_co),
    IAQI_no2 = unlist(IAQI_no2)
  ) %>% 
  mutate(borough = recode(borough, "The Bronx" = "Bronx")) # Tweaking naming and structure for combo with covid data

```

```{r 2019 air quality data cleaning, include = FALSE}
# Data import and cleaning
AQI_2019 =
  tibble(
    path = list.files("./data/AQI_data_2019") # Listing all file names
    ) %>% 
  mutate(
    path = str_c("./data/AQI_data_2019/", path), # Completing the paths
    data = map(path, fread) # Reading the data for each path
    ) %>% 
  unnest(data) %>% 
  janitor::clean_names() %>% 
  filter(country == "US") %>%
  filter(city == "Brooklyn" | city == "Queens" | city == "The Bronx" | city == "Staten Island" | city == "Manhattan") %>%
  mutate(borough = city) %>%
  select(-c(city, country)) %>%
  pivot_wider(names_from = "specie", values_from = c("count", "min", "max", "median", "variance")) %>% 
  select(date, borough, median_pm25, median_o3, median_co, median_no2)

# Generate IAQIs, determine AQI and AQI category based on max IAQI per day, for 2019
AQI_2019 =
  AQI_2019 %>%
  mutate(
    median_co = as.character(median_co),
    median_co = recode(median_co, "500" = "5"), # Recoding what seems to be data entry errors
    median_co = as.numeric(median_co)) %>% 
  mutate(
    IAQI_o3 = map(median_o3, IAQI_formula_o3), #notice similar code to 2020
    IAQI_pm25 = map(median_pm25, IAQI_formula_pm25),
    IAQI_co = map(median_co, IAQI_formula_co),
    IAQI_no2 = map(median_no2, IAQI_formula_no2)
    ) %>%
  rowwise() %>% 
  mutate(
    AQI = max(IAQI_o3, IAQI_pm25, IAQI_co, IAQI_no2, na.rm = TRUE),
    AQI_category =
      if_else(
        AQI <= 50 & AQI >= 0,
        "Good",
        if_else(
          AQI <= 100 & AQI > 50,
          "Moderate",
          if_else(
            AQI <= 150 & AQI > 100,
            "Unhealthy for Sensitive Populations",
            "Unhealthy")
          )
        ),
    IAQI_o3 = unlist(IAQI_o3),
    IAQI_pm25 = unlist(IAQI_pm25),
    IAQI_co = unlist(IAQI_co),
    IAQI_no2 = unlist(IAQI_no2)
  ) %>% 
  filter(date > "2018-12-31") %>% # Remove 2018 dates from the 2019 dataset, raw data had them
  mutate(borough = recode(borough, "The Bronx" = "Bronx")) # Tweaking naming and structure for combo with covid data

```

```{r merge 2019 and 2020 air quality data, include = FALSE}
# Merge 2019 and 2020 AQI
AQI_2019_and_2020 =
  rbind(AQI_2019, AQI_2020) %>% 
  as_tibble() %>% 
  mutate(
    date = as.Date(date, tryFormats = c("%Y-%m-%d"))
  )
```

```{r by borough covid data cleaning, include = FALSE}
# Prep covid data, initial cleaning
nyc_daily_borough_testing = 
  read_csv(
      "./data/covid_data/nyc_daily_covid.csv") %>% 
  janitor::clean_names() %>% 
  rename(date = date_of_interest) %>% 
  mutate(
    date = as.Date(date, format = "%m/%d/%Y"),
    date = as.Date(date, tryFormats = c("%Y-%m-%d"))
  ) %>%
  pivot_longer(
    bx_case_count:si_death_count_7day_avg,
    names_to = "borough_variable",
    values_to = "observed_value"
  ) %>% 
  mutate(
    borough_variable = str_replace(borough_variable, "bx_", "Bronx/"),
    borough_variable = str_replace(borough_variable, "bk_", "Brooklyn/"),
    borough_variable = str_replace(borough_variable, "qn_", "Queens/"),
    borough_variable = str_replace(borough_variable, "si_", "Staten Island/"),
    borough_variable = str_replace(borough_variable, "mn_", "Manhattan/")
  ) %>% 
  separate(borough_variable, into = c("borough", "observation_type"), sep = "/") %>% 
  arrange(date, borough, observation_type, observed_value) %>% 
  pivot_longer(
    case_count:incomplete,
    names_to = "total_observation_type",
    values_to = "total_observed_value"
  ) %>% 
  filter(observation_type == c("case_count", "case_count_7day_avg"))
```

```{r merge air quality and covid data, echo = F}
AQI_covid_master = #join covid and the full 2019-2020 aqi data
  left_join(nyc_daily_borough_testing, AQI_2019_and_2020, by = c("date", "borough"))
```

```{r, echo = F}
total_AQI = AQI_covid_master %>% #create the rolling averages for the AQI
  select(date, borough, AQI) %>% 
  distinct(date, borough, .keep_all = TRUE) %>% 
  group_by(date) %>% 
  mutate(avg_AQI = mean(AQI)) %>% 
  ungroup() %>% 
  select(date, avg_AQI) %>% 
  distinct(date, .keep_all = TRUE) %>% 
  arrange(date) %>% 
  mutate(AQI_7day_avg = zoo::rollmean(avg_AQI, k = 7, fill = NA))
```

```{r vline function, echo = F}
vline <- function(x = 0, color = "black") { #brief function to create flexible vertical line shapes on plotly
  list(
    type = "line", 
    y0 = 0, 
    y1 = 0.9, 
    yref = "paper",
    x0 = x, 
    x1 = x, 
    line = list(color = "black", opacity = 0.5, dash = "solid", width = 0.5)
  )
}

hline <- function(y = 0, color = "black") { #brief function to create flexible vertical line shapes on plotly
  list(
    type = "line", 
    y0 = y, 
    y1 = y, 
    xref = "paper",
    x0 = 0, 
    x1 = 1, 
    line = list(color = "black", opacity = 0.1, dash = "dash", width = 1)
  )
}
```

```{r, include = F}
AQI_total_2019 = # steps to take the difference in 2020 AQI values from 2019 AQI values. Distinct by date and borough, first group by date, and then generate the mean and prep for join
  AQI_2019 %>% 
  select(date, borough, AQI) %>% 
  distinct(date, borough, .keep_all = TRUE) %>% 
  group_by(date) %>% 
  mutate(avg_AQI = mean(AQI)) %>% 
  ungroup() %>% 
  select(date, avg_AQI) %>% 
  distinct(date, .keep_all = TRUE) %>% 
  separate(date, into = c("year","month","day"), sep = "-") %>% 
  mutate(avg_AQI_2019 = avg_AQI) %>% 
  select(-avg_AQI)

AQI_total_2020 = # same as 2019 
  AQI_2020 %>% 
  select(date, borough, AQI) %>% 
  distinct(date, borough, .keep_all = TRUE) %>% 
  group_by(date) %>% 
  mutate(avg_AQI = mean(AQI)) %>% 
  ungroup() %>% 
  select(date, avg_AQI) %>% 
  distinct(date, .keep_all = TRUE) %>% 
  separate(date, into = c("year","month","day"), sep = "-")
  
AQI_dif = right_join(AQI_total_2019, AQI_total_2020, by = c("month", "day")) %>% #join by date, rolling 7 day average
  drop_na(avg_AQI) %>% 
  filter(year.x == 2019,
         year.y == 2020) %>% 
  mutate(AQI_dif = avg_AQI - avg_AQI_2019) %>% # note taking difference in average (overall) AQI
  mutate(year = year.y) %>% 
  select(year, month, day, AQI_dif) %>% 
  unite("date", year:day, sep = "-") %>% 
  mutate(date = as.Date(date)) %>% 
  arrange(date) %>% 
  mutate(AQI_dif_7day_avg = zoo::rollmean(AQI_dif, k = 7, fill = NA))

AQI_covid_master = left_join(AQI_covid_master, AQI_dif, by = "date") #and join this to the covid dataset for full visualization

```

```{r,include = F}
# Calculating CO IAQI percentage change by borough

IAQI_co_borough_2019 = # a similar process is used for CO data specifically
  AQI_2019 %>% 
  select(date, borough, IAQI_co) %>% 
  rename(IAQI_co_2019 = IAQI_co) %>%
  mutate(date = str_remove(date, "2019-")) 
  
IAQI_co_borough_2020 =
  AQI_2020 %>% 
  select(date, borough, IAQI_co) %>% 
  rename(IAQI_co_2020 = IAQI_co) %>%
  mutate(date = str_remove(date, "2020-"))

IAQI_co_borough_dif =
  right_join(IAQI_co_borough_2019, IAQI_co_borough_2020, by = c("date", "borough")) %>%  
  mutate(IAQI_co_dif = IAQI_co_2020 - IAQI_co_2019) %>%  #note this is for CO specifically
  drop_na(IAQI_co_dif) %>% 
  select("date", "borough", "IAQI_co_dif") %>% 
  mutate(
    date = str_c("2020-", date),
    date = as.Date(date)
  ) %>%
  group_by(borough) %>% 
  arrange(date) %>% 
  mutate(IAQI_co_dif_7day_avg = zoo::rollmean(IAQI_co_dif, borough, k = 7, fill = NA)) %>% #similar rolling average
  drop_na(IAQI_co_dif_7day_avg) %>% 
  ungroup()

AQI_covid_master = left_join(AQI_covid_master, IAQI_co_borough_dif, by = c("date", "borough"))
```

```{r}
#add a color manipulation object to the plots
our_oranges = brewer.pal(n = 9, "Oranges")[5:9] #select the top 5 of the 9 orange colors to make the orange on the graph easier to see
```


Time Series Plots
===================================== 

Row
-------------------------------------

### AQI Difference from 2019 and COVID-19 Case Count Over Time
```{r plotly line plot 1, echo = F}
#plot_ly1, the overall AQI_7day_avg and NYC-wide case count
# first line is shiny infrastructure
renderPlotly({ 
  AQI_covid_master %>% #pass dataframe
  mutate(
    text_label_1 = str_c("Date: ", date, "\nAQI Difference from 2019: ", round(AQI_dif_7day_avg, 2)),
    text_label_2 = str_c("Date: ", date, "\nCOVID-19 Case Count: ", total_observed_value)
    ) %>% #generated text labels for the plotly
  filter(observation_type == c("case_count")) %>% 
  filter(total_observation_type == c("case_count")) %>% #filter to include only the covid observation category of interest (case count)
  plot_ly(
      x = ~date,
      y = ~AQI_dif_7day_avg, #air quality averages differenced trace
      name = "AQI Difference from 2019",
      type = "scatter",
      mode = "lines",
      opacity = 0.8,
      text = ~text_label_1, #assign the text label for AQI to this trace
      line = list(color = "#FFCD58"), #set color to differ from subsequent graph for clarity
      hoverinfo = "text"
      ) %>%
    add_trace(
      x = ~date,
      y = ~total_observed_value, #covid case count trace
      type = "scatter",
      mode = "lines",
      name = "COVID-19 Case Count",
      line = list(color = "#005EFF"), #manually set color for synchrony with plot 2
      opacity = 1,
      text = ~text_label_2, #assign the text label for covid case count for this trace
      yaxis = "y2",
      inherit = FALSE,
      hoverinfo = "text") %>%  #covid data
    add_trace( #first text trace date label
      x = c("2020-03-22"), #these 2 next traces set vertical lines for 90% of the y-axis height that are labelled with the policy change
      y0 = 0, 
      y1 = 0.9, 
      yref = "paper",
      type = "scatter",
      mode = "lines",
      name = "",
      text = c("PAUSE Order"),
      showlegend = FALSE, 
      color = "black",
      line = list(color = "#000000") #black
    ) %>%  #covid data
    add_trace( #second text trace date label
      x = c("2020-06-08"),
      y0 = 0, 
      y1 = 0.9, 
      yref = "paper",
      type = "scatter",
      mode = "lines",
      name = "",
      text = c("Phase 1 Opening"),
      showlegend = FALSE,
      line = list(color = "#000000") #black
    ) %>% 
    layout(
      shapes = list(vline("2020-03-22"), vline("2020-06-08"), hline(0)), #set the policy shapes, and a horizontal line at y=0 to show improvement vs decline in AQI
      xaxis = list(title = "Date"),
      yaxis = list(side = "left", title = "AQI Difference from 2019 (7 Day Average)", showgrid = FALSE, zeroline = FALSE),
      yaxis2 = list(side = "right", overlaying = "y", title = "COVID-19 Case Count", showgrid = FALSE, zeroline = FALSE,autotick = F, tickmode = "array", tickvals = c(0,1000,2000,3000,4000) #we manually set these yaxis 2 values to exclude 5000 and 6000 since the legent kept overlapping the axis; this was the only solution effective
)
     )
})
```

Row
-------------------------------------

### Carbon Monoxide IAQI Difference from 2019 by Borough and COVID-19 Case Count Over Time
```{r plotly line plot 2, echo = F}
#plotly2, the per-borough AQI rolling average and the per-borough nyc case count
#similar structure to previous plotly. Shiny architecture and then plot each trace, this time with a per-borough nuance
renderPlotly({
  AQI_covid_master %>%
    mutate(
    text_label_3 = str_c("Date: ", date, "\nBorough: ", borough, "\nCO IAQI Difference from 2019: ", round(IAQI_co_dif_7day_avg, 2)),
    text_label_4 = str_c("Date: ", date, "\nCOVID-19 Case Count: ", total_observed_value)
    ) %>% 
    mutate(borough_titles = str_c(borough)) %>% 
    filter(total_observation_type == "case_count") %>% 
    plot_ly(
      x = ~date,
      y = ~IAQI_co_dif_7day_avg, #notice CO per borough
      split = ~borough_titles,
      type = "scatter",
      mode = "lines",
      opacity = 0.8,
      text = ~text_label_3,
      color = ~borough_titles,
      colors = ~our_oranges, #using our custom oranges palette
      hoverinfo = "text"
    ) %>% 
    add_trace(
      x = ~date,
      y = ~total_observed_value,
      type = "scatter",
      mode = "lines",
      line = list(color = "#005EFF"), #color alignment with previous, as noted
      opacity = 1,
      text = ~text_label_4,
      yaxis = "y2",
      inherit = FALSE,
      name = "COVID-19 Cases",
      hoverinfo = "text"
      ) %>% 
    add_trace( #first text trace date label
      x = c("2020-03-22"),
      y0 = 0, 
      y1 = 0.9, 
      yref = "paper",
      type = "scatter",
      mode = "lines",
      name = "",
      text = c("PAUSE Order"),
      showlegend = FALSE,
      line = list(color = "#000000") 
    ) %>%  #covid data
    add_trace( #second text trace date label
      x = c("2020-06-08"),
      y0 = 0, 
      y1 = 0.9, 
      yref = "paper",
      type = "scatter",
      mode = "lines",
      name = "",
      text = c("Phase 1 Opening"),
      showlegend = FALSE,
      line = list(color = "#000000")
    ) %>% 
    layout(
      legend = list(title = list(text = "Select a Borough")),
      shapes = list(vline("2020-03-22"), vline("2020-06-08"), hline(0)),
      xaxis = list(title = "Date"),
      yaxis = list(side = "left", title = "Carbon Monoxide IAQI Difference from 2019 (7 Day Average)", showgrid = FALSE, zeroline = FALSE),
      yaxis2 = list(side = "right", overlaying = "y", title = "COVID-19 Case Count", showgrid = FALSE, zeroline = FALSE, autotick = F, tickmode = "array", tickvals = c(0,1000,2000,3000,4000)
)
      )
  })
```

Map
===================================== 

Row {data-height = 1500}
-------------------------------------
```{r echo = F}
borough_coord = tibble("borough" = c("Bronx", "Manhattan", "Brooklyn", "Queens", "Staten Island"), "latitude" = c(40.8448, 40.7731, 40.6782, 40.7282, 40.5795), "longitude" = c(-73.8648, -73.9712, -73.9442, -73.7949, -74.1502)) #establish coordinates for each borough location to show up
color_df = colorFactor(c("green", "yellow", "orange", "red"), domain = c("Good", "Moderate", "Unhealthy for Sensitive Populations", "Unhealthy")) #establish colors for each of the air quality categories
AQI_covid_master = AQI_covid_master %>% 
  left_join(borough_coord, by = "borough") # join with borough coordinates 
output$map = renderLeaflet({ 
  AQI_covid_master %>% 
    filter(date == input[["date"]]) %>% 
    mutate(popup = str_c("<strong>", borough, "</strong>", "<br/>", "Date: ", date, "<br/>", "Air Quality Category: ", AQI_category, "<br/>", "Air Quality Index: ", round(AQI, 2), "<br/>", "Carbon Monoxide Level: ", lapply(IAQI_co, round, 2)) %>% #set the popup text
    map(htmltools::HTML)) %>%
    leaflet() %>% #pipe into leaflet for interactive mapping
    addTiles() %>% 
    setView(-73.95, 40.7228, zoom = 11) %>% #default view for visibility
    addProviderTiles("CartoDB.Positron") %>% 
    addCircleMarkers( #set the borough markers
      radius = 20,
      lng = ~longitude,
      lat = ~latitude,
      stroke = FALSE,
      fillOpacity = 0.8, 
      color = ~color_df(AQI_category),
      label = ~popup
    ) %>% 
    addLegend("bottomright", colors = c("green", "yellow", "orange", "red"),
              labels = c("Good", "Moderate", "Unhealthy for Sensitive Populations", "Unhealthy"),
              title = "Air Quality Index")
})
leafletOutput('map', height=1000)
```

Row {.sidebar}
-------------------------------------

Use the selector below to examine AQI by borough on a given date.

```{r input, echo = F}
  dateInput( #date selector
      "date",
      label = h3("Date:"),
      value = "2020-02-29", # Default value
      min = "2020-02-29", # Min value
      max = "2020-11-14") # Max value
```

