---
title: "NYC Air Quality Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r dashboard setup, include = FALSE}
# Libraries
library(flexdashboard)
library(leaflet)
library(tidyverse)
library(httr)
library(data.table)
library(shiny)
library(plotly)

# Theme
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r air quality data cleaning 2020, include = FALSE}
# Data import and cleaning 
air_quality = fread("./data/waqi-covid19-airqualitydata-2020.csv") %>%
  filter(Country == "US") %>%
  filter(City == "Brooklyn" | City == "Queens" | City == "The Bronx" | City == "Staten Island" | City == "Manhattan") %>%
  mutate(borough = City) %>%
  select(-c(City,Country)) %>%
  pivot_wider(names_from = "Specie", values_from = c("count","min","max","median","variance")) %>% 
  janitor::clean_names()

fwrite(air_quality,"./data/Just_NYC_Air_Quality_Data.csv")

# Adding air quality index
AQI_temp = air_quality %>%
  select(date,borough,median_pm25,median_o3,median_co,median_no2)

AQI_formula_O3 = function(AQI){
  if (AQI <= 54 && AQI >= 0 ){
    AQI_O3 = (50/54)*(AQI-0) + 0
  }
}

AQI_formula_pm25 = function(AQI){
  if (AQI<= 12&& AQI>=0 ){
    AQI_pm25 = (50/12)*(AQI-0) + 0
  }
  
  else if (AQI<=35.4 && AQI>=12.1 ){
    AQI_pm25 = (50/23.3)*(AQI-12.1) + 51
  }
  
  else if (AQI<=55.4 && AQI>=35.5 ){
    AQI_pm25 = (50/19.9)*(AQI-35.5) + 101
  }
  
  else{
    AQI_pm25 = (50/94.9)*(AQI-55.5) + 151
  }
}

AQI_formula_co = function(AQI){
  if (AQI<= 4.4&& AQI>=0 ){
    AQI_co = (50/4.4)*(AQI-0) + 0
  }
  
  else if (AQI<=9.4 && AQI>=4.5 ){
    AQI_co = (50/4.9)*(AQI-4.5) + 51
  }
  
  else{
    AQI_co = (50/2.9)*(AQI-12.4) + 101
  }
}

AQI_formula_no2 = function(AQI){
  if (AQI<= 53&& AQI>=0 ){
    AQI_no2 = (50/53)*(AQI-0) + 0
  }
  
  else if (AQI<=100 && AQI>=54 ){
    AQI_no2 = (50/46)*(AQI-54) + 51
  }
  
  else{
    AQI_no2 = (50/259)*(AQI-101) + 101
  }
}

AQI_O3 = AQI_temp%>%
  select(median_o3)%>%
  purrr::map(~AQI_formula_O3(.x))%>%
  data.frame()

AQI_pm25 = AQI_temp%>%
  select(median_pm25)%>%
  purrr::map(~AQI_formula_pm25(.x))%>%
  data.frame()

AQI_co = AQI_temp%>%
  select(median_co)%>%
  purrr::map(~AQI_formula_co(.x))%>%
  data.frame()

AQI_no2 = AQI_temp%>%
  select(median_no2)%>%
  purrr::map(~AQI_formula_no2(.x))%>%
  data.frame()

AQI_combined_2020 = cbind(AQI_O3,AQI_co,AQI_no2,AQI_pm25)%>%
  rowwise() %>% 
  mutate(AQI = max(median_o3,median_co,median_no2,median_pm25,na.rm=T))%>%
  cbind(air_quality%>%pull(date),
        air_quality%>%pull(borough))
colnames(AQI_combined_2020) = c("AQI_o3","AQI_co","AQI_no2","AQI_pm25","AQI_Final","date","borough")

AQI_combined_2020 = AQI_combined_2020%>%
  select(c("date","borough","AQI_Final","AQI_o3","AQI_co","AQI_no2","AQI_pm25"))%>%
  mutate(AQI_Category = if_else(
    AQI_Final<=50 & AQI_Final>=0,"Good",
    if_else(AQI_Final<=100&AQI_Final>50,"Moderate",
    if_else(AQI_Final<=150&AQI_Final>100,"Unhealthy for Sensitive Populations","Unhealthy"))))


fwrite(AQI_combined_2020,"./data/Air_Quality_Data_with_AQI.csv")
```



```{r air quality data cleaning 2019, include = FALSE}
library(data.table)
library(tidyverse)
# setwd("./data/2019_Data/")
# files = list.files(".")
# air_quality_2019 = files %>%        
#   map(~ fread(.x)) %>%
#   reduce(rbind)%>%
#   filter(Country == "US") %>%
#   filter(City == "Brooklyn" | City == "Queens" | City == "The Bronx" | City == "Staten Island" | City == "Manhattan")%>%
#   mutate(borough = City) %>%
#   filter(Specie == "pm25" | Specie == "temperature"| Specie == "o3" | Specie == "no2" | Specie == "co")%>%
#   select(-c(City,Country,variance,count))%>%
#   distinct()%>%
#   tidyr::pivot_wider(names_from = Specie, values_from = c(median,max,min))
# 
# 
# fwrite(air_quality_2019,"Just_NYC_Air_Quality_Data_2019.csv")

AQI_temp = fread("./data/2019_data/Just_NYC_Air_Quality_Data_2019.csv")%>%
  select(Date,borough,median_pm25,median_o3,median_co,median_no2)

AQI_formula_O3 = function(AQI){
  if (AQI<=54 && AQI>=0 ){
    AQI_O3 = (50/54)*(AQI-0) + 0
  }
  
  else if (AQI<=70 && AQI>54 ){
    AQI_O3 = (50/22)*(AQI-55) + 51
  }
  
  else if (AQI<=85 && AQI>70){
    AQI_O3 = (50/14)*(AQI-70) + 101
  }
  
  else if (AQI<=105 && AQI>85 ){
    AQI_O3 = (50/19)*(AQI-86) + 151
  }
  
  else if (AQI<=200 && AQI>105 ){
    AQI_O3 = (99/94)*(AQI-106) + 201
  }
  
  else if (AQI<=404 && AQI>204){
    AQI_O3 = (99/199)*(AQI-205) + 201
  }
  
  else{
    AQI_O3 = (199/199)*(AQI-405) + 301
  }
}

AQI_formula_pm25 = function(AQI){
  if (AQI<= 12&& AQI>=0 ){
    AQI_pm25 = (50/12)*(AQI-0) + 0
  }
  
  else if (AQI<=35.4 && AQI>=12.1 ){
    AQI_pm25 = (50/23.3)*(AQI-12.1) + 51
  }
  
  else if (AQI<=55.4 && AQI>=35.5 ){
    AQI_pm25 = (50/19.9)*(AQI-35.5) + 101
  }
  
  else if (AQI<=150.4 && AQI>=55.5 ){
    AQI_pm25 = (50/94.9)*(AQI-55.5) + 151
  }
  
  else{
    AQI_pm25 = (99/99.9)*(AQI-150.5) + 201
  }
}

AQI_formula_co = function(AQI){
  if (AQI<= 4.4&& AQI>=0 ){
    AQI_co = (50/4.4)*(AQI-0) + 0
  }
  
  else if (AQI<=9.4 && AQI>=4.5 ){
    AQI_co = (50/4.9)*(AQI-4.5) + 51
  }
  
  else{
    AQI_co = (199/19.9)*(AQI-30.5) + 301
}
}

AQI_formula_no2 = function(AQI){
  if (AQI<= 53&& AQI>=0 ){
    AQI_no2 = (50/53)*(AQI-0) + 0
  }
  
  else if (AQI<=100 && AQI>=54 ){
    AQI_no2 = (50/46)*(AQI-54) + 51
  }
  
  else{
    AQI_no2 = (50/259)*(AQI-101) + 101
  }
}

AQI_O3 = AQI_temp%>%
  select(median_o3)%>%
  purrr::map(~AQI_formula_O3(.x))%>%
  data.frame()

AQI_pm25 = AQI_temp%>%
  select(median_pm25)%>%
  purrr::map(~AQI_formula_pm25(.x))%>%
  data.frame()

AQI_co = AQI_temp%>%
  select(median_co)%>%
  purrr::map(~AQI_formula_co(.x))%>%
  data.frame()

AQI_no2 = AQI_temp%>%
  select(median_no2)%>%
  purrr::map(~AQI_formula_no2(.x))%>%
  data.frame()

AQI_combined_2019 = cbind(AQI_O3,AQI_co,AQI_no2,AQI_pm25)%>%
  rowwise() %>% 
  mutate(AQI = max(median_o3,median_co,median_no2,median_pm25,na.rm=T))%>%
  cbind(AQI_temp%>%pull(Date),
        AQI_temp%>%pull(borough))%>%
  filter(AQI != -Inf)

colnames(AQI_combined_2019) = c("AQI_o3","AQI_co","AQI_no2","AQI_pm25","AQI_Final","date","borough")

AQI_combined_2019 = AQI_combined_2019%>%
  select(c("date","borough","AQI_Final","AQI_o3","AQI_co","AQI_no2","AQI_pm25"))%>%
  mutate(AQI_Category = if_else(
    AQI_Final<=50 & AQI_Final>=0,"Good",
    if_else(AQI_Final<=100&AQI_Final>50,"Moderate",
    if_else(AQI_Final<=150&AQI_Final>100,"Unhealthy for Sensitive Populations",if_else(AQI_Final<=200&AQI_Final>150,"Unhealthy",if_else(AQI_Final<=300&AQI_Final>200,"Very Unhealthy","Hazardous"))))))


fwrite(AQI_combined_2019,"./data/2019_Data/Air_Quality_Data_with_AQI_2019.csv")
```

```{r merge 2019 and 2020 Air Quality Data, include = F}
data_2019 = fread("./data/2019_Data/Air_Quality_Data_with_AQI_2019.csv")%>%
  mutate(date = as.character(date))%>%
  separate(date, into = c("year","month","day"),sep="-")

data_2020 = fread("./data/Air_Quality_Data_with_AQI.csv")%>%
  mutate(date = as.character(date))%>%
  separate(date, into = c("year","month","day"),sep="-")

combined = merge(data_2019,data_2020,by=c("month","day","borough"))%>%
  mutate(Adjusted_Value = AQI_Final.y*100/AQI_Final.x)%>%
  filter(year.x!=year.y) %>% #x values correspond to 2019 and y values correspond to 2020
  arrange(borough, month, day, year.x, AQI_Final.x, year.y, AQI_Final.y, Adjusted_Value) 

fwrite(combined,"./data/AQI_2019_AND_2020.csv",sep=",")
```
```{r nyc-wide covid data cleaning, include = FALSE}
nyc_cases =
  GET("https://data.cityofnewyork.us/resource/rc75-m7u3.csv") %>% # Reading in the data
  content("parsed") %>% 
  rename(date = date_of_interest) %>% # Renaming the date variable for simplicity
  select(date, case_count) %>% # Only retaining date and case count for simplicity
  mutate(
    date = as.Date(date, tryFormats = c("%Y-%m-%d")) # as.Date() by default cannot convert POSIXct to date; no data lost
  )
## Note: This dataset also contains hospitalized count and death count.
## I removed those measures for now for simplicity, but we can always decide to retain them later if we think they would be useful.
```

```{r by borough covid data cleaning, cache = TRUE, include = FALSE}
nyc_daily_borough_testing =
  read_csv(
      "./data/covid_data/nyc_daily_covid.csv") %>% 
  janitor::clean_names() %>% 
  rename(date = date_of_interest) %>% 
  mutate(
    date = as.Date(date, format = "%m/%d/%Y")
  ) %>%
  pivot_longer(
    bx_case_count:si_death_count_7day_avg,
    names_to = "borough_variable",
    values_to = "observed_value"
  ) %>% 
  mutate(
    borough_variable = str_replace(borough_variable, "bx_", "Bronx/"),
    borough_variable = str_replace(borough_variable, "bk_", "Brooklyn/"),
    borough_variable = str_replace(borough_variable, "qn_", "Queens/"),
    borough_variable = str_replace(borough_variable, "si_", "Staten Island/"),
    borough_variable = str_replace(borough_variable, "mn_", "Manhattan/")
  ) %>% 
  separate(borough_variable, into = c("borough", "observation_type"), sep = "/") %>% 
  arrange(date, borough, observation_type, observed_value) %>% 
  pivot_longer(
    case_count:incomplete,
    names_to = "total_observation_type",
    values_to = "total_observed_value"
  ) %>% 
  filter(observation_type == c("case_count", "case_count_7day_avg"))

# Add proof-of-concept covid policy changes to df
nyc_daily_borough_testing = 
  nyc_daily_borough_testing %>% 
  mutate(
    policy_change = case_when(
      date == "2020-03-07" ~ "State of Emergency",
      date == "2020-03-22" ~ "PAUSE Order",
      date == "2020-08-08" ~ "Phase 1 Opening",
      date == "2020-10-01" ~ "Primary Schools Open"),
    dates_vline = date,
    dates_vline = case_when(
      date == "2020-03-07" ~ "TRUE",
      date == "2020-03-22" ~ "TRUE",
      date == "2020-08-08" ~ "TRUE",
      date == "2020-10-01" ~ "TRUE")
  )

#Create joined dataset of COVID and Air Quality 
nyc_daily_borough_testing = 
  nyc_daily_borough_testing %>% 
  mutate(
    date_merge = as.Date(date, format = "%m/%d/%Y")
  ) 
AQI_combined_2020 = 
AQI_combined_2020 %>% 
  mutate(
    date_merge = as.numeric(date)
  ) %>% 
    mutate(
      date_merge = as.Date(date_merge, origin = "1970-01-01")
  )

covid_air_ytd_joined = left_join(
  nyc_daily_borough_testing, AQI_combined_2020, by = "date_merge") %>% 
  select(-date.y, -borough.y) %>% 
  rename(
    date = date.x,
    borough = borough.x
  ) %>% 
  mutate(
    borough = as.factor(borough)
  )
```

```{r example covid line graphs, eval = FALSE}
# Quick plot of covid cases by borough
nyc_daily_borough_testing %>% 
  filter(observation_type == c("case_count")) %>% 
  filter(total_observation_type == c("case_count")) %>% 
  group_by(date, borough, observation_type) %>% 
  ggplot(aes(x = date)) + 
  geom_line(aes(x = date, y = observed_value, color = borough, alpha = 0.5)) +
  geom_line(aes(x = date, y = total_observed_value, alpha = 0.5,  group = total_observation_type)) +
  geom_smooth(
    aes(x = date, y = observed_value, color = borough), 
        alpha = 0.8, se = F,
    method = "gam") +
  geom_smooth(
    aes(x = date, y = total_observed_value), 
        alpha = 0.8, se = F) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d", limits = as.Date(c("2020-03-01", "2020-12-01"))) +
  coord_cartesian(ylim = c(0, 6000)) +
  labs(
    title = "Case Count per NYC Borough over Time",
    x = "Week Number",
    y = "Value",
    caption = "P8105 Final Project")

# Quick plot of covid 7 day avg with reference lines
nyc_daily_borough_testing %>% 
  filter(observation_type == c("case_count_7day_avg")) %>% 
  group_by(date, borough, observation_type) %>% 
  ggplot(aes(x = date, y = observed_value, color = borough)) + 
  geom_line() +
  geom_vline(xintercept = as.numeric(
    as.Date(
      c("2020-03-07","2020-03-22", "2020-08-08", "2020-10-01"))),  
    linetype = 2) +
  geom_text(
    aes(x = as.Date("2020-03-07"),
                label = c("State of Emergency Declared"), 
        y = 1000), 
    alpha = 0.5, colour = "red", angle = 90, vjust = -1, text = element_text(size = 6)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d", limits = as.Date(c("2020-03-01", "2020-12-01"))) +
  coord_cartesian(ylim = c(0,2000)) +
  labs(
    title = "7 Day Case Count Average per NYC Borough over Time",
    x = "Week Number",
    y = "Value",
    caption = "P8105 Final Project")

```

```{r example air quality plots, eval=FALSE}
air_quality %>% 
  ggplot(aes(x = date, y = median_co, color = borough)) + 
    geom_point(alpha = .2) +
    geom_line(alpha = .75, size = .75) +
      scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(
    title = "Median CO Emmissions over Time for each NYC borough, 2020",
    x = "Month",
    y = "Median CO (Parts per Million)",
    caption = "Examining COVID-19 Incidence, P8105 Final Project") 

air_quality %>% 
  ggplot(aes(x = date, y = median_pm25, color = borough)) + 
    geom_point(alpha = .2) +
    geom_line(alpha = .75, size = .75) +
      scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(
    title = "Median Particulate Matter (size<2.5 micrometers) Levels over Time for each NYC borough, 2020",
    x = "Month",
    y = "Median Particulate Matter (size < 2.5 micrometeres) Levels (Parts per Millon)",
    caption = "Examining COVID-19 Incidence, P8105 Final Project") 

air_quality %>% 
  ggplot(aes(x = date, y = median_temperature, color = borough)) + 
    geom_point(alpha = .2) +
    geom_line(alpha = .75, size = .75) +
      scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(
    title = "Median Temperature over Time for each NYC borough, 2020",
    x = "Month",
    y = "Median Temperature (degrees C)",
    caption = "Examining COVID-19 Incidence, P8105 Final Project")

AQI_combined_2020 %>% 
  group_by(borough) %>% 
  ggplot(aes(x = date, y = AQI_Final)) +
  geom_line() +
  geom_smooth()
```



Column {.sidebar}
-----------------------------------------------------------------------

Here we can write some introductory text/explain our project.

```{r input}
 dateInput(
    "date",
    label = h3("Date input"),
    value = "2020-02-29", # Default value
    min = "2020-02-29", # Min value
    max = "2020-11-17") # Max value

# I put in these dates based on the covid dataset, but we can update as needed
```

Column {data-width=500}
-----------------------------------------------------------------------

### COVID Cases and Air Quality Index

```{r covid and air quality plots}

#renderPlotly({
#covid_air_ytd_joined %>% 
#  filter(observation_type == c("case_count")) %>% 
#  filter(total_observation_type == c("case_count")) %>% 
#  group_by(date, borough) %>% 
#  summarize(sum_cases = sum(observed_value)) %>% 
#  plot_ly(x = ~date, y = ~sum_cases,  type = "scatter", color = ~borough, colors = "viridis")
#})



covid_air_ytd_joined %>% 
  filter(observation_type == c("case_count")) %>% 
  filter(total_observation_type == c("case_count")) %>% 
  group_by(date, borough) %>% 
  ggplot(aes(x = date)) + 
  geom_line(
    aes(x = date, y = observed_value, color = borough),
    alpha = 0.8) +
  geom_line(
    aes(x = date, y = total_observed_value,  group = total_observation_type), 
    alpha = 0.8) +
  geom_smooth(
    aes(x = date, y = observed_value, color = borough), 
        alpha = 0.8, se = F,
    method = "gam") +
  geom_smooth(
    aes(x = date, y = total_observed_value), 
        alpha = 0.8, se = F) +
  geom_line(
    aes(x = date, y = total_observed_value,  group = total_observation_type),
    alpha = 0.8) +
  geom_line(
    aes(x = date, y = AQI_Final*32.30644095, group = borough),
    alpha = 0.05) +
  geom_smooth(
    aes(x = date, y = AQI_Final*32.30644095,  color = borough),
    alpha = 0.05) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b %d",
    limits = as.Date(c("2020-03-01", "2020-12-01"))) +
  scale_y_continuous(
    name = "COVID Case Count",
    sec.axis = sec_axis(~./32.30644095, name = "AQI Index")) +
  coord_cartesian(ylim = c(0, NA)) +
  labs(
    title = "Case Count and AQI per NYC Borough over Time",
    x = "Week Number",
    y = "Value",
    caption = "P8105 Final Project")
```


Column {data-width=500}
-----------------------------------------------------------------------

### Air Quality Index by Borough

```{r}
borough_coord = tibble("borough" = c("The Bronx", "Manhattan", "Brooklyn", "Queens", "Staten Island"), "latitude" = c(40.8448, 40.7731, 40.6782, 40.7282, 40.5795), "longitude" = c(-73.8648, -73.9712, -73.9442, -73.7949, -74.1502))

color_df = colorFactor(c("green", "yellow", "orange", "red"), domain = c("Good", "Moderate", "Unhealthy for Sensitive Populations", "Unhealthy"))

AQI_combined_2020 = AQI_combined_2020 %>% 
  left_join(borough_coord, by = "borough")


renderLeaflet({
  AQI_combined_2020 %>% 
    filter(date == input[["date"]]) %>% 
    leaflet() %>%
    addTiles() %>%
    setView(-73.95, 40.7228, zoom = 11) %>%
    addProviderTiles("CartoDB.Positron") %>% 
    addCircleMarkers(
      radius = 20,
      lng = ~longitude,
      lat = ~latitude,
      stroke = FALSE,
      fillOpacity = 0.8, 
      color = ~color_df(AQI_Category),
      label = ~borough
    )
})
```

